---
title: "Appendix"
author: "ZiqianHe"
output: pdf_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(data.table)
library(boot)
knitr::opts_chunk$set(echo = TRUE)
```

```{r include=FALSE}
set.seed(124)
n <- 16
p_C <- 1/5
C <- rbinom(n,1,p_C)
theta0 <- 1/2
theta1 <- -1/5
p_A <- theta0+theta1*C
A <- rbinom(n,1,p_A)
beta0 <- 110
beta1 <- 20
beta2 <- 5
sigma_Y <- 1
mu_Y <- beta0+beta1*C+beta2*A
Y <- rnorm(n,mu_Y, sigma_Y)

```

## d
```{r}
mean(Y[A==1])-mean(Y[A==0])
```

## e
```{r}
dt = data.table(Y=Y,A=A,C=C)

#without boostrap
mean(dt[A==1][C==0]$Y)
mean(dt[A==1][C==1]$Y) #means no data
mean(dt[A==0][C==0]$Y)
mean(dt[A==0][C==1]$Y) 

E_Y1 = mean(dt[A==1][C==0]$Y)*0.8
E_Y0 = mean(dt[A==0][C==0]$Y)*0.8 + mean(dt[A==0][C==1]$Y)*0.2
E_Y1-E_Y0

#boostrap
dt$interv <- -1 # 1st copy: equal to original one

interv0 <- dt # 2nd copy: treatment set to 0, outcome to missing
interv0$interv <- 0
interv0$A <- 0
interv0$Y <- NA

interv1 <- dt # 3rd copy: treatment set to 1, outcome to missing
interv1$interv <- 1
interv1$A <- 1
interv1$Y <- NA

onesample <- rbind(dt, interv0, interv1) # combining datasets

standardization <- function(data, indices) {
  # create a dataset with 3 copies of each subject
  d <- data[indices, ] # 1st copy: equal to original one`
  d$interv <- -1
  d0 <- d # 2nd copy: treatment set to 0, outcome to missing
  d0$interv <- 0
  d0$A <- 0
  d0$Y <- NA
  d1 <- d # 3rd copy: treatment set to 1, outcome to missing
  d1$interv <- 1
  d1$A <- 1
  d1$Y <- NA
  d.onesample <- rbind(d, d0, d1) # combining datasets
  
  # linear model to estimate mean outcome conditional on treatment and confounders
  # parameters are estimated using original observations only (interv= -1)
  # parameter estimates are used to predict mean outcome for observations with set
  # treatment (interv=0 and interv=1)
  fit <- glm(
    Y ~ A + as.factor(C),
    data = d.onesample
  )
  
  d.onesample$predicted_meanY <- predict(fit, d.onesample)
  
  # estimate mean outcome in each of the groups interv=-1, interv=0, and interv=1
  return(c(
    mean(d.onesample$predicted_meanY[d.onesample$interv == -1]),
    mean(d.onesample$predicted_meanY[d.onesample$interv == 0]),
    mean(d.onesample$predicted_meanY[d.onesample$interv == 1]),
    mean(d.onesample$predicted_meanY[d.onesample$interv == 1]) -
      mean(d.onesample$predicted_meanY[d.onesample$interv == 0])
  ))
}

# bootstrap
results <- boot(data = dt,
                statistic = standardization,
                R = 5)

# generating confidence intervals
se <- c(sd(results$t[, 1]),
        sd(results$t[, 2]),
        sd(results$t[, 3]),
        sd(results$t[, 4]))
mean <- results$t0
ll <- mean - qnorm(0.975) * se
ul <- mean + qnorm(0.975) * se

bootstrap <-
  data.frame(cbind(
    c(
      "Observed",
      "No Treatment",
      "Treatment",
      "Treatment - No Treatment"
    ),
    mean,
    se,
    ll,
    ul
  ))

bootstrap
```
